### ISSUE TITLE
询问不均衡数据的f1关系

### ISSUE THREAD

**Issue by chensuim** [chenghuige/wenzheng#2]
hello chenghuige:
有幸看到您的答辩ppt，关于这个比赛，我看到数据十分不均横，但是比赛给出了macro f1, 我想问下的单独个例的f1分布是不是也不均衡？
是否单独对于一个方面的f1是否和该例的正例占比相关？比如“交通是否便利”下“未提及大概占了85%，负面和中性都只有3%左右，正面有10%左右，请问它们各自的f1是否有较大差别？是否正例比例大的更容易达到较高的f1？

谢谢
chensui

**Comment by chenghuige** [comment]
这部分我没有监控关注你说的这个问题，应该确实是正例比例大的更容易更高f1 ，相对好学习。比例低的最简单的规则策略就是扩大一下召回 这样对应macro f1 会提升分值。

**Comment by chensuim** [comment]
谢谢
