### ISSUE TITLE
PPT有点糊

### ISSUE THREAD

**Issue by nlpjoe** [chenghuige/wenzheng#3]
作者您好，这个PPT有点糊，请问能提供更清晰版本的PPT查看或者下载么？

**Comment by chenghuige** [comment]
@nlpjoe 可以在这里下载
https://files.cnblogs.com/files/rocketfan/%E7%AD%94%E8%BE%A9_%E7%BB%86%E7%B2%92%E5%BA%A6%E7%94%A8%E6%88%B7%E8%AF%84%E8%AE%BA%E6%83%85%E6%84%9F%E5%88%86%E6%9E%90_%E5%90%8E%E5%8E%82%E6%9D%91%E9%9D%99%E9%9D%99.pptx

**Comment by googlx** [comment]
大神，这个链接好像失效了，能再发一下吗，十分感谢！
