### ISSUE TITLE
请教关于用ELMo预训练语言模型的问题

### ISSUE THREAD

**Issue by xuehui0725** [chenghuige/wenzheng#4]
您好，关于用ELMo预训练语言模型，有两个问题想请教下：
（1）请问在torch-lm-train.py中怎么看ELMo对应的model，是在这个路径下吗？wenzheng/utils/lele/layers/elmo/
（2）“注意目前的设计只能单层elmo如果多层需要再修改代码因为目前是stack rnn第二层就等于loss作弊了“，stack rnn第二层怎么理解？elmo是用单层的双向LSTM训练，然后基于elmo输出的词向量在建立双向LSTM模型＋rnet输出＋pooling吗？

**Comment by chenghuige** [comment]
@xuehui0725 
(1)wenzheng/projects/ai2018/sentiment/torch-lm-train.py 参考这个文件 
主要代码在wenzheng/wenzheng/pyt/encoder.py
(2)是的pretrain是单层，finetune是单层上面再加一层变成双层。stack rnn 第二层的话用的是第一层的输出（从左到右，从右到左的拼接），这个就已经用到从左到有，从右到左的序列信息了，所以再预测就是loss作弊了
